server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username:
    password:
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

logging:
  level:
    lol.cicco: debug

executor:
  corePoolSize: 10
  maxPoolSize: 20
  queueCapacity: 100
