server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/admin
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

logging:
  level:
    lol.cicco: debug

executor:
  corePoolSize: 10
  maxPoolSize: 20
  queueCapacity: 100
